import { test, expect } from '@playwright/test';

// Pages containing strategy or pattern content — snapshot their <main> text
// so any migration that changes visible content is caught immediately.
// Run `npx playwright test --update-snapshots` to regenerate after intentional changes.
const CONTENT_PAGES = [
  'pattern/patt-1.html',
  'pattern/patt-2.html',
  'pattern/patt-3.html',
  'pattern/patt-4.html',
  'pattern/patt-5.html',
  'pattern/patt-6.html',
  'pattern/patt-7.html',
  'pattern/patt-8.html',
  'pattern/patt-9.html',
  'pattern/patt-10.html',
  'pattern/patt-11.html',
  'pattern/patt-12.html',
  'pattern/patt-13.html',
  'pattern/patt-14.html',
  'pattern/patt-15.html',
  'pattern/patt-16.html',
  'pattern/patt-17.html',
  'pattern/patt-18.html',
  'pattern/patt-19.html',
  'pattern/patt-20.html',
  'pattern/patt-21.html',
  'pattern/patt-22.html',
  'pattern/patt-23.html',
  'pattern/patt-24.html',
  'pattern/patt-25.html',
  'pattern/patt-26.html',
  'pattern/patt-27.html',
  'pattern/patt-28.html',
  'pattern/patt-29.html',
  'pattern/patt-30.html',
  'pattern/patt-31.html',
  'a-helpfull-path-for-getting-started.html',
  'aggregate-patterns.html',
  'description-scenarios.html',
  'descriptions-what-i-do.html',
  'descriptions-what-i-know.html',
  'discovering-new-strategies-and-patterns.html',
  // 'fundamentals-what-i-do.html',
  'fundamentals-what-i-know.html',
  'fundamentals-who-i-know.html',
  'guiding-the-effort-with-major-activities-and-components.html',
  'identifying-system-purpose-and-features.html',
  'interaction-patterns.html',
  'list-of-patterns.html',
  'list-of-strategies-activities-and-model-components.html',
  'list-of-strategies-discovering-new-strategies-and-patterns.html',
  'list-of-strategies-establishing-responsibilities.html',
  'list-of-strategies-identifying-system-purpose-and-features.html',
  'list-of-strategies-selecting-objects.html',
  'list-of-strategies-working-out-dynamics-with-scenarios.html',
  'list-of-strategies.html',
  'message-traffic-what-i-do.html',
  'model-components-hi-dm-what-i-do.html',
  'model-components-hi-dm-who-i-know.html',
  'model-components-hi-what-i-know.html',
  'pattern-players-what-i-do.html',
  'pattern-players-what-i-know.html',
  'pattern-players-who-i-know.html',
  'plan-patterns.html',
  'real-time-what-i-do.html',
  'selecting-objects-analogies.html',
  'selecting-objects-kinds-of-objects.html',
  'selecting-objects-model-components.html',
  'selecting-objects-names.html',
  // 'selecting-objects-pattern-players.html',
  'selecting-objects-reuse.html',
  'selecting-objects-what-to-consider-and-challenge.html',
  'the-basics-scenarios.html',
  'the-fundamental-pattern.html',
  'transaction-patterns.html',
  'what-to-consider-and-challenge-gen-spec-with-attributes-what-i-know.html',
  'what-to-consider-and-challenge-scenarios.html',
  'what-to-consider-and-challenge-what-i-do-gen-spec-with-services.html',
  'what-to-consider-and-challenge-what-i-do-names.html',
  'what-to-consider-and-challenge-what-i-do-responsibilities.html',
  'what-to-consider-and-challenge-what-i-know-names.html',
  'what-to-consider-and-challenge-what-i-know-values.html',
  'what-to-consider-and-challenge-who-i-know.html',
  'where-to-put-a-service-what-i-do.html',
];

for (const pagePath of CONTENT_PAGES) {
  test.skip(`content: ${pagePath}`, async ({ page }) => {
    await page.goto(pagePath);
    const content = await page.locator('main').textContent();
    expect(content).toMatchSnapshot(`${pagePath}.txt`);
  });
}
