import { test, expect } from '@playwright/test';

// Pages containing strategy or pattern content — snapshot their <main> text
// so any migration that changes visible content is caught immediately.
// Run `npx playwright test --update-snapshots` to regenerate after intentional changes.
const CONTENT_PAGES = [
  '1-collection-worker-pattern-the-fundamental-pattern.html',
  '2-actor-participant-pattern-transaction-patterns.html',
  '3-participant-transaction-pattern-transaction-patterns.html',
  '4-place-transaction-pattern-transaction-patterns.html',
  '5-specific-item-transaction-pattern-transaction-patterns.html',
  '6-transaction-transaction-line-item-pattern-transaction-patterns.html',
  '7-transaction-subsequent-transaction-pattern-transaction-patterns.html',
  '8-transaction-line-item-subsequent-transaction-line-item-pattern-transaction-patterns.html',
  '9-item-line-item-pattern-transaction-patterns.html',
  '10-specific-item-line-item-pattern-transaction-patterns.html',
  '11-item-specific-item-pattern-transaction-patterns.html',
  '12-associate-other-associate-pattern-transaction-patterns.html',
  '13-specific-item-hierarchical-item-pattern-transaction-patterns.html',
  '14-container-content-pattern-aggregate-patterns.html',
  '15-container-container-line-item-pattern-aggregate-patterns.html',
  '16-group-member-pattern-aggregate-patterns.html',
  '17-assembly-part-pattern-aggregate-patterns.html',
  '18-compound-part-part-pattern-aggregate-patterns.html',
  '19-packet-packet-component-pattern-aggregate-patterns.html',
  '20-plan-step-pattern-plan-patterns.html',
  '21-plan-plan-execution-pattern-plan-patterns.html',
  '22-step-step-execution-pattern-plan-patterns.html',
  '23-plan-execution-step-execution-pattern-plan-patterns.html',
  '24-plan-plan-version-pattern-plan-patterns.html',
  '25-peer-peer-pattern-interaction-patterns.html',
  '26-proxy-specific-item-pattern-interaction-patterns.html',
  '27-publisher-subscriber-pattern-interaction-patterns.html',
  '28-sender-pass-through-receiver-pattern-interaction-patterns.html',
  '29-sender-lookup-receiver-pattern-interaction-patterns.html',
  '30-caller-dispatcher-caller-back-pattern-interaction-patterns.html',
  '31-gatekeeper-request-resource-pattern-device-patterns.html',
  'a-helpfull-path-for-getting-started.html',
  'aggregate-patterns.html',
  'description-scenarios.html',
  'descriptions-what-i-do.html',
  'descriptions-what-i-know.html',
  'discovering-new-strategies-and-patterns.html',
  'fundamentals-what-i-do.html',
  'fundamentals-what-i-know.html',
  'fundamentals-who-i-know.html',
  'guiding-the-effort-with-major-activities-and-components.html',
  'identifying-system-purpose-and-features.html',
  'interaction-patterns.html',
  'list-of-patterns.html',
  'list-of-strategies-activities-and-model-components.html',
  'list-of-strategies-discovering-new-strategies-and-patterns.html',
  'list-of-strategies-establishing-responsibilities.html',
  'list-of-strategies-identifying-system-purpose-and-features.html',
  'list-of-strategies-selecting-objects.html',
  'list-of-strategies-working-out-dynamics-with-scenarios.html',
  'list-of-strategies.html',
  'message-traffic-what-i-do.html',
  'model-components-hi-dm-what-i-do.html',
  'model-components-hi-dm-who-i-know.html',
  'model-components-hi-what-i-know.html',
  'pattern-players-what-i-do.html',
  'pattern-players-what-i-know.html',
  'pattern-players-who-i-know.html',
  'plan-patterns.html',
  'real-time-what-i-do.html',
  'selecting-objects-analogies.html',
  'selecting-objects-kinds-of-objects.html',
  'selecting-objects-model-components.html',
  'selecting-objects-names.html',
  'selecting-objects-pattern-players.html',
  'selecting-objects-reuse.html',
  'selecting-objects-what-to-consider-and-challenge.html',
  'the-basics-scenarios.html',
  'the-fundamental-pattern.html',
  'transaction-patterns.html',
  'what-to-consider-and-challenge-gen-spec-with-attributes-what-i-know.html',
  'what-to-consider-and-challenge-scenarios.html',
  'what-to-consider-and-challenge-what-i-do-gen-spec-with-services.html',
  'what-to-consider-and-challenge-what-i-do-names.html',
  'what-to-consider-and-challenge-what-i-do-responsibilities.html',
  'what-to-consider-and-challenge-what-i-know-names.html',
  'what-to-consider-and-challenge-what-i-know-values.html',
  'what-to-consider-and-challenge-who-i-know.html',
  'where-to-put-a-service-what-i-do.html',
];

for (const pagePath of CONTENT_PAGES) {
  test(`content: ${pagePath}`, async ({ page }) => {
    await page.goto(pagePath);
    const content = await page.locator('main').textContent();
    expect(content).toMatchSnapshot(`${pagePath}.txt`);
  });
}
